<?php

namespace ContainerDGGEP2o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6BZjHaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6B_ZjHa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6B_ZjHa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'doctrine' => '?',
            'validator' => '?',
        ]);
    }
}
