<?php

namespace ContainerDGGEP2o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BxvcbvZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bxvcbvZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bxvcbvZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentTicketController::index' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\CommentTicketController::next' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\CommentTicketController::sort' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\NewPostController::postTicket' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\RegController::registration' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\index::index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CommentTicketController:index' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\CommentTicketController:next' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\CommentTicketController:sort' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\NewPostController:postTicket' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\RegController:registration' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\index:index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CommentTicketController::index' => '?',
            'App\\Controller\\CommentTicketController::next' => '?',
            'App\\Controller\\CommentTicketController::sort' => '?',
            'App\\Controller\\NewPostController::postTicket' => '?',
            'App\\Controller\\RegController::registration' => '?',
            'App\\Controller\\index::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CommentTicketController:index' => '?',
            'App\\Controller\\CommentTicketController:next' => '?',
            'App\\Controller\\CommentTicketController:sort' => '?',
            'App\\Controller\\NewPostController:postTicket' => '?',
            'App\\Controller\\RegController:registration' => '?',
            'App\\Controller\\index:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
