<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS7SbnJi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS7SbnJi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS7SbnJi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS7SbnJi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS7SbnJi\App_KernelDevDebugContainer([
    'container.build_hash' => 'S7SbnJi',
    'container.build_id' => '89d29d99',
    'container.build_time' => 1647798284,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS7SbnJi');
